### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by 471448446** [AlanLiu90/FixThreadAffinity#1]
您好：
请问如何使用呢，是直接将Asstes/Plugins/ThreadAffinity复制到项目里面就可以吗？（unity小白，请见谅）

**Comment by AlanLiu90** [comment]
需要复制`Asstes/Plugins/ThreadAffinity`目录和`Assets/ThreadHelper.cs`，然后在运行时调用`ThreadHelper.SetAffinity`，调用方式可以参考`Assets/TestThreadAffinity.cs`。

**Comment by 471448446** [comment]
好的，十分感谢
